CREATE TABLE PEOPLE2
   (	ID NUMBER,
	NAME VARCHAR2(100),
	EMAIL VARCHAR2(200),
	 PRIMARY KEY (ID)
  USING INDEX  ENABLE
   ) ;
-- GRANTS --

  GRANT DELETE ON PEOPLE2 TO A_RS;
  GRANT INSERT ON PEOPLE2 TO A_RS;
  GRANT SELECT ON PEOPLE2 TO A_RS;
  GRANT UPDATE ON PEOPLE2 TO A_RS;
